[env]
TERM = "xterm-256color"

[general]
import = [
  # uncomment the flavour you want below:
   "~/.config/alacritty/themes/catpuccin/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml",
  #  "~/.config/alacritty/themes/alacritty-theme/noctis_lux.toml"
]

[font]
normal.family="MesloLGS Nerd Font Mono"
size = 16

[window]
dimensions = { columns = 100, lines = 20 }

