# Instructions:  
# 1. make sure to install the following before using this 
# brew install starship
# brew install zsh-autosuggestions
# brew install eza
# brew install nvim
# brew install tmux
# brew install zsh-syntax-highlighting
# brew install asdf

# 2. make sure to set the correct paths for the source-ing of zsh files towards the bottom of this doc
# echo "source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh" >> ~/.zshrc
# echo "source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" >> ~/.zshrc
# zsh-syntax-highlighting.zsh should be the last line of the zshrc file

export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin:$PATH"

# starship init
eval "$(starship init zsh)"

# history setup
# https://www.josean.com/posts/how-to-setup-alacritty-terminal
HISTFILE=$HOME/.zhistory
SAVEHIST=1000
HISTSIZE=999
setopt share_history
setopt hist_expire_dups_first
setopt hist_ignore_dups
setopt hist_verify

# completion using arrow keys (based on history)
bindkey '^[[A' history-search-backward
bindkey '^[[B' history-search-forward

# thanks to Claude
# Double-tap ESC to clear line
KEYTIMEOUT=50  # Reduces key sequence timeout (default is 40)
bindkey '\e\e' kill-whole-line

# hasan's custom aliases
alias ls="eza --icons=always"
alias edit="nvim"
md() {
    mkdir -p "$1" && cd "$1"
}
alias ..='cd ..'
alias ...='cd ../..'
alias ll='ls -lah'
alias home='cd ~'
alias tm2="tmux new-session \; split-window -h"
alias tmk="tmux kill-server"
alias tmls="tmux list-sessions"

# Extract any archive - thanks to Claude
extract() {
    if [ -f $1 ]; then
        case $1 in
            *.tar.bz2)   tar xjf $1     ;;
            *.tar.gz)    tar xzf $1     ;;
            *.bz2)       bunzip2 $1     ;;
            *.rar)       unrar e $1     ;;
            *.gz)        gunzip $1      ;;
            *.tar)       tar xf $1      ;;
            *.tbz2)      tar xjf $1     ;;
            *.tgz)       tar xzf $1     ;;
            *.zip)       unzip $1       ;;
            *.Z)         uncompress $1  ;;
            *)           echo "'$1' cannot be extracted" ;;
        esac
    else
        echo "'$1' is not a valid file"
    fi
}

# plugins

source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh

. /opt/homebrew/opt/asdf/libexec/asdf.sh

# this should be at the bottom of zshrc 
source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

